CRUD with current user and log
hovnaz/black-mulberry pull request #37
Opened 2022-11-08 17:30 UTC by MesropMkhitaryan

2022-11-09 09:37 UTC, Mushegh128 requested changes

2022-11-09 09:37 UTC, Mushegh128 commented on black-mulberry-core/src/main/java/com/black/mulberry/core/mapper/ProductMapper.java
> +
this is unnessacery lines, delete them

2022-11-09 09:37 UTC, Mushegh128 commented on black-mulberry-core/src/main/java/com/black/mulberry/core/mapper/ProductMapper.java
> +import java.util.List;
this is unused import. delete them

2022-11-09 09:37 UTC, Mushegh128 commented on black-mulberry-core/src/main/java/com/black/mulberry/core/service/ProductService.java
> +    List<Product> findAll();
menq paymanavorvel einq or entity chenq return ene, lutshe het poxes

2022-11-09 09:37 UTC, Mushegh128 commented on black-mulberry-core/src/main/java/com/black/mulberry/core/service/impl/ProductServiceImpl.java
> +            throw new NullPointerException("category is null");
@nchi null pointer kqces? sik infakti bune brat, veranaye sax motodt ira logerov handerdz, dir erkar mtace u pordze du qezi sxal ban gtnis u uxxes, inchqan krnas sax kataryali ber or sorvis.

2022-11-16 12:55 UTC, Mushegh128 requested changes

2022-11-16 12:55 UTC, Mushegh128 commented on black-mulberry-core/src/main/java/com/black/mulberry/core/service/impl/CategoryProductImpl.java
> +            log.debug("category with id: {} not found", categoryId);
sik DEBUG log che, ari poxenq kam ERROR kak WARN

2022-11-16 12:55 UTC, Mushegh128 commented on black-mulberry-core/src/main/java/com/black/mulberry/core/service/impl/ProductServiceImpl.java
> +        Optional<User> userOptional = userRepository.findById(user.getId());
servicid mej uninq arden ger user by ID, krnas @dik ogtagorces es nuyn ban@ stexe chexni.

2022-11-16 12:55 UTC, Mushegh128 commented on black-mulberry-core/src/main/java/com/black/mulberry/core/service/impl/ProductServiceImpl.java
> +        product.setUser(userOptional.get());
stex null_i het krna arnchvinq

2022-11-16 12:55 UTC, Mushegh128 commented on black-mulberry-core/src/main/java/com/black/mulberry/core/service/impl/ProductServiceImpl.java
> +            log.debug("product with id: {} not found", id);
ERROR kam WARN

2022-11-16 12:55 UTC, Mushegh128 commented on black-mulberry-core/src/main/java/com/black/mulberry/core/service/impl/ProductServiceImpl.java
> +            log.debug("product with id: {} not found", productId);
sik el

2022-11-16 12:55 UTC, Mushegh128 commented on black-mulberry-core/src/main/java/com/black/mulberry/core/service/impl/ProductServiceImpl.java
> +            return IOUtils.toByteArray(inputStream);
bac connection kmna , sra masin xosacel enq - dir try with resourcesi mej

2022-11-16 12:55 UTC, Mushegh128 commented on black-mulberry-mvc/src/main/java/com/black/mulberry/mvc/controller/ProductController.java
>      @GetMapping("/product/add")
controlleri vra areq misht ogtagorcenq @RequestMapping("/v1/product") , isk @GetMapping("/product/add")  -> @GetMapping("/add"). hame URL_in nayelov es khasknam or sik praduct avelcnelu url e, bayc metodt uxxaki ej@ kuda , ed pah@ myam veranayeq u hisheq or @GetMaping@ body chuni.

es paragayum krnas nayes tarberak urdex or ej bacelu gorcoxutyun enox URL_nerd kexnin orinak _> "nav/product_new"

2022-11-16 12:55 UTC, Mushegh128 commented on black-mulberry-rest/src/main/java/com/black/mulberry/rest/endpoint/ProductEndpoint.java
>  @RequestMapping("/products")
"v1/products"

2022-11-16 13:06 UTC, hovnaz commented on black-mulberry-core/src/main/java/com/black/mulberry/core/service/impl/ProductServiceImpl.java
> +        Optional<User> userOptional = userRepository.findById(user.getId());
verevy todo e grac et masy mtacel enk. userService-i mejinery sagh DTO kveradardzne et patcharov cheink krna miangamic service-ic kancheink

2022-11-16 13:09 UTC, hovnaz commented on black-mulberry-core/src/main/java/com/black/mulberry/core/service/impl/ProductServiceImpl.java
> +        product.setUser(userOptional.get());
chisht es bayc menk hashvi enk arel es pahy, chuzecank null-i stugum anteghi grel vordev petq e UserSerive-ic kanchenk hetagayum u UserSerive-i mej et pahy arden hashvi e arac

2022-11-16 13:10 UTC, hovnaz commented on black-mulberry-mvc/src/main/java/com/black/mulberry/mvc/controller/ProductController.java
>      @GetMapping("/product/add")
sik imijayloc mvc-n e u sagh petq e poxvi enqan or dzevapoxel enk or build@ ancni

2022-11-16 13:14 UTC, Mushegh128 commented on black-mulberry-core/src/main/java/com/black/mulberry/core/service/impl/ProductServiceImpl.java
> +        product.setUser(userOptional.get());
karevor@ chmoranaq

2022-11-16 13:16 UTC, Mushegh128 commented on black-mulberry-mvc/src/main/java/com/black/mulberry/mvc/controller/ProductController.java
>      @GetMapping("/product/add")
ed url@ shat texer kogtagorcvi? vsyo taki @RequestMaping avelacnel@ url chi poxe motd, bayc v1 avelacnel@ stex cankali e

2022-11-16 13:16 UTC, hovnaz commented on black-mulberry-core/src/main/java/com/black/mulberry/core/service/impl/ProductServiceImpl.java
> +        product.setUser(userOptional.get());
ytor hamar todo enk grel:D

2022-11-19 13:14 UTC, Mushegh128 approved these changes

2022-11-19 13:37 UTC, merged