Bmt2 58 product list pagination
hovnaz/black-mulberry pull request #49
Opened 2022-11-28 13:39 UTC by MesropMkhitaryan

2022-11-28 14:20 UTC, hovnaz commented on black-mulberry-core/src/main/java/com/black/mulberry/core/repository/ProductRepository.java
> +    List<Product> findAllByIsDeleteFalseAndUserIdOrderByCreateAtDesc(long userId, Pageable pageable);
Ապ ախպոր պես IsDeleteFalse-ը վերջում տար

2022-11-28 14:21 UTC, hovnaz commented on black-mulberry-rest/src/main/java/com/black/mulberry/rest/endpoint/ProductEndpoint.java
> +    }
currentUser-ը ունի getId(0  ըտիկ օգտագործե

2022-11-28 14:22 UTC, hovnaz commented on black-mulberry-rest/src/main/java/com/black/mulberry/rest/endpoint/ProductEndpoint.java
>      }
նույնից

2022-11-28 14:23 UTC, hovnaz commented on black-mulberry-rest/src/main/java/com/black/mulberry/rest/endpoint/ProductEndpoint.java
> +        return ResponseEntity.ok(productService.countAllByUserId(currentUser.getUser().getId()));
նույնից

2022-11-28 15:16 UTC, Mushegh128 requested changes

2022-11-28 15:16 UTC, Mushegh128 commented on black-mulberry-core/src/main/java/com/black/mulberry/core/repository/ProductRepository.java
> +    List<Product> findAllByIsDeleteFalseAndUserIdOrderByCreateAtDesc(long userId, Pageable pageable);
txeq jan myam pordzeq sik ete chisht khishe asc desc@ krnanq vorpes argument tanq , aysinqn 2i tex@ me metodov enenq

2022-11-29 16:06 UTC, Mushegh128 approved these changes

2022-11-29 16:40 UTC, merged