Bmt2 78 product search/filter
hovnaz/black-mulberry pull request #62
Opened 2022-12-13 18:20 UTC by MesropMkhitaryan

2022-12-14 17:02 UTC, Mushegh128 requested changes

2022-12-14 17:02 UTC, Mushegh128 commented on black-mulberry-core/src/main/java/com/black/mulberry/core/service/impl/ProductSearchServiceImpl.java
> +        if (productFilterRequest.getTitle() != null && !productFilterRequest.getTitle().equals("")){
ba vor equals exav " "_i ?
Stringi het ashxatelu hamar ogtagorce apach.lang3.StringUtits.isNotBlank

2022-12-14 17:02 UTC, Mushegh128 commented on black-mulberry-core/src/main/java/com/black/mulberry/core/service/impl/ProductSearchServiceImpl.java
> +        if (productFilterRequest.getDescription() != null && !productFilterRequest.getDescription().equals("")){
StringUtils.isNotBlank()

2022-12-14 17:02 UTC, Mushegh128 commented on black-mulberry-rest/src/main/java/com/black/mulberry/rest/endpoint/ProductEndpoint.java
> +    public List<ProductResponse> searchProduct(@RequestBody ProductFilterRequest productFilterRequest) {
Get zapros@ Body chuni, krnam entadrem or es mas@ run erac u pordzac che. poxe brat

2022-12-14 17:02 UTC, Mushegh128 commented on black-mulberry-rest/src/main/java/com/black/mulberry/rest/endpoint/ProductEndpoint.java
> +    public List<ProductResponse> getAllFilteredProducts(@RequestBody ProductFilterRequest productFilterRequest) {
stexel body petq che

2022-12-15 11:08 UTC, hovnaz commented on black-mulberry-core/src/main/java/com/black/mulberry/core/service/impl/ProductSearchServiceImpl.java
> +        if (productFilterRequest.getTitle() != null && !productFilterRequest.getTitle().equals("")){
dra hamar prosty chen dne artagre. hasknalovvvvv

2022-12-15 16:57 UTC, Mushegh128 requested changes

2022-12-15 16:57 UTC, Mushegh128 commented on black-mulberry-core/pom.xml
> -                        <processor>com.querydsl.apt.jpa.JPAAnnotationProcessor</processor>
@hovnaz  sik naye chishte or jnjvele ?

2022-12-15 16:57 UTC, Mushegh128 commented on black-mulberry-data-transfer/src/main/java/com/black/mulberry/data/transfer/request/ProductFilterRequest.java
> +    @NotEmpty
Stringi hamar ogtagoce @NotBlank.
bayc spes moment -> ProductServiceImpl.searchForProduct_i miji StringUtis.(productFilterRequest.getTitle()) stugumd misht TRUE kuda vortev ed request modeld controlleri mej validaciya kancni.

myam veranaye ed pah@

2022-12-15 16:57 UTC, Mushegh128 commented on black-mulberry-rest/src/main/java/com/black/mulberry/rest/endpoint/ProductEndpoint.java
> +    public List<ProductResponse> searchProduct(ProductFilterRequest productFilterRequest) {
anotacian jnjelov Get metod@ body chi unena , kam poxe Post dardzra (vorn or lav gaxapar che , bayc lucum e) , kam inch data or petq e @RequestParamov vercra

u ete guzes Request modeld validacia ancni javax>validationi koxmic kam spring validaciayi koxmic bdi avelcnes @Valid anotaciyan metodi mej 

EX: @PostMapping("/lyalyalya")
	public ResponseEntity<ResponseModel> sayLya(@Valid @NotNull @RequestBody Requestrequest) {
}

u kantralyori anotacvi org.springframework.validation.annotation.Validated anotacian or request metodit miji validacnox anotacianer@ ashxati. 

anpayman sonq eneluc heto myam postmanov zapros era debag rejimov u hamozvi or 400 kstanas + breackpontd chi erta araj(nu chbdi brne)

2022-12-15 16:57 UTC, Mushegh128 commented on black-mulberry-rest/src/main/java/com/black/mulberry/rest/endpoint/ProductEndpoint.java
> +    public List<ProductResponse> getAllFilteredProducts(ProductFilterRequest productFilterRequest) {
-

2022-12-16 14:22 UTC, MesropMkhitaryan commented on black-mulberry-core/pom.xml
> -                        <processor>com.querydsl.apt.jpa.JPAAnnotationProcessor</processor>
ha sig pti jnjver

2022-12-17 11:42 UTC, merged